insert into contact (first_name, last_name, email, phone, status, created_at) values
  ('Марија',    'Костовска',    'm.kostovska@huddle.mk',    '+389 70 111 222', 'ONLINE',  now()),
  ('Томислав',  'Стојков',      't.stojkov@huddle.mk',      '+389 70 333 444', 'BUSY',    now()),
  ('Ана',       'Митревска',    'a.mitrevska@huddle.mk',    '+389 70 555 666', 'ONLINE',  now()),
  ('Емил',      'Блажевски',    'e.blazevski@huddle.mk',    '+389 70 777 888', 'OFFLINE', now()),
  ('Петар',     'Николов',      'p.nikolov@huddle.mk',      '+389 70 999 000', 'OFFLINE', now()),
  ('Сара',      'Јовановска',   's.jovanovska@huddle.mk',   '+389 71 100 200', 'ONLINE',  now()),
  ('Никола',    'Петрески',     'n.petreski@huddle.mk',     '+389 71 200 300', 'BUSY',    now()),
  ('Елена',     'Стефановска',  'e.stefanovska@huddle.mk',  '+389 71 300 400', 'ONLINE',  now());

insert into meeting (title, description, status, scheduled_at, started_at, ended_at, created_by) values
  ('Sprint планирање',
   'Планирање на Q2 sprint со тимот — задачи, рокови, одговорности',
   'ACTIVE',
   now(),
   now(),
   null,
   'admin'),

  ('1:1 со Томислав',
   'Неделен 1:1 разговор — напредок и блокери',
   'ENDED',
   now() - interval '1 day 2 hours',
   now() - interval '1 day 2 hours',
   now() - interval '1 day 1 hour',
   'admin'),

  ('Retro – Април',
   'Ретроспектива на изминатиот месец — што оди добро, што треба да се подобри',
   'ENDED',
   now() - interval '3 days',
   now() - interval '3 days',
   now() - interval '3 days' + interval '1 hour 20 minutes',
   'admin'),

  ('Design review – нов UI',
   'Преглед на новиот дизајн на апликацијата со тимот',
   'SCHEDULED',
   now() + interval '4 hours',
   null,
   null,
   'admin'),

  ('Client demo – Тетекс',
   'Демо на апликацијата за клиентот Тетекс АД',
   'SCHEDULED',
   now() + interval '2 days',
   null,
   null,
   'admin'),

  ('Backend sync',
   'Технички состанок за API интеграција и архитектурни одлуки',
   'SCHEDULED',
   now() + interval '4 days',
   null,
   null,
   'admin'),

  ('Planning Q3',
   'Квартално планирање — цели, KPI и буџет за Q3',
   'SCHEDULED',
   now() + interval '8 days',
   null,
   null,
   'admin'),

  ('Team building',
   'Тимски настан — неформален разговор и планирање на следната четвртина',
   'SCHEDULED',
   now() + interval '15 days',
   null,
   null,
   'admin');

insert into meeting_participants (meeting_id, contact_id) values
  (1, 1), (1, 2), (1, 3), (1, 7),
  (2, 2),
  (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6),
  (4, 1), (4, 3), (4, 8),
  (5, 1), (5, 2), (5, 3), (5, 4),
  (6, 2), (6, 3), (6, 5), (6, 7),
  (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8),
  (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8);

insert into meeting_note (content, written_by, created_at, updated_at, meeting_id) values
  ('Договоривме 3 главни задачи: Auth модул, Dashboard UI и API интеграција.',
   'admin', now(), now(), 1),
  ('Рокот е 15-ти. Секој член го зема по еден таск и го пријавува во Jira.',
   'admin', now(), now(), 1),
  ('Разговаравме за блокерот со LiveKit конекцијата — решено со промена на CORS конфиг.',
   'admin', now() - interval '1 day 1 hour 30 minutes', now() - interval '1 day 1 hour 30 minutes', 2),
  ('Ретроспективата покажа дека треба подобрување на комуникацијата помеѓу frontend и backend тимот.',
   'admin', now() - interval '3 days' + interval '1 hour', now() - interval '3 days' + interval '1 hour', 3),
  ('Следен спринт фокус: перформанси, bug fixing и подготовка за клиентски демо.',
   'admin', now() - interval '3 days' + interval '1 hour 10 minutes', now() - interval '3 days' + interval '1 hour 10 minutes', 3);
